import { Priority, TodoDTO } from "@/types/taskTypes";

// export const demoMockTasksArray: TodoDTO[] = [
//   {
//     todoId: 106,
//     title: "Denne går ut 30. Juni",
//     description: "",
//     status: {
//       statusId: 7,
//       statusCode: "CREATED",
//       statusName: "Created",
//       description: "Task has been created",
//     },
//     priority: Priority.MEDIUM,
//     dueDate: new Date("2024-06-30T23:59:59"),
//     createdAt: new Date("2024-06-30T00:00:00"),
//     updatedAt: new Date("2024-06-30T00:00:00"),
//     files: [],
//     content: undefined,
//     tags: [],
//     sortIndex: 6,
//   },
//   {
//     todoId: 101,
//     title: "Denne går ut 1. Juli",
//     description: "",
//     status: {
//       statusId: 7,
//       statusCode: "CREATED",
//       statusName: "Created",
//       description: "Task has been created",
//     },
//     priority: Priority.MEDIUM,
//     dueDate: new Date("2024-07-01T23:59:59"),
//     createdAt: new Date("2024-07-01T00:00:00"),
//     updatedAt: new Date("2024-07-01T00:00:00"),
//     files: [],
//     content: undefined,
//     tags: [],
//     sortIndex: 1,
//   },
//   {
//     todoId: 102,
//     title: "Denne går ut 2. Juli",
//     description: "",
//     status: {
//       statusId: 7,
//       statusCode: "CREATED",
//       statusName: "Created",
//       description: "Task has been created",
//     },
//     priority: Priority.MEDIUM,
//     dueDate: new Date("2024-07-02T23:59:59"),
//     createdAt: new Date("2024-07-02T00:00:00"),
//     updatedAt: new Date("2024-07-02T00:00:00"),
//     files: [],
//     content: undefined,
//     tags: [],
//     sortIndex: 2,
//   },
// ];

export const demoMockTasksArray: TodoDTO[] = [
  {
    todoId: 106,
    title: "Fix a bug in the comments section",
    description:
      "Resolve the issue causing comments to not display correctly on post pages.",
    status: {
      statusId: 7,
      statusCode: "CREATED",
      statusName: "Created",
      description: "Task has been created",
    },
    priority: Priority.HIGH,
    dueDate: new Date("2024-06-30T23:59:59"),
    createdAt: new Date("2024-06-30T00:00:00"),
    updatedAt: new Date("2024-06-30T00:00:00"),
    files: [],
    content: undefined,
    tags: ["bug", "comments", "urgent"],
    sortIndex: 6,
  },
  {
    todoId: 101,
    title: "Implement new authentication flow",
    description: "Integrate OAuth2 for user login and registration.",
    status: {
      statusId: 7,
      statusCode: "CREATED",
      statusName: "Created",
      description: "Task has been created",
    },
    priority: Priority.HIGH,
    dueDate: new Date("2024-07-01T23:59:59"),
    createdAt: new Date("2024-07-01T00:00:00"),
    updatedAt: new Date("2024-07-01T00:00:00"),
    files: [],
    content: undefined,
    tags: ["feature", "authentication", "security"],
    sortIndex: 1,
  },
  {
    todoId: 102,
    title: "Code review for team",
    description: "Review and provide feedback on the latest pull requests.",
    status: {
      statusId: 7,
      statusCode: "CREATED",
      statusName: "Created",
      description: "Task has been created",
    },
    priority: Priority.MEDIUM,
    dueDate: new Date("2024-07-02T23:59:59"),
    createdAt: new Date("2024-07-02T00:00:00"),
    updatedAt: new Date("2024-07-02T00:00:00"),
    files: [],
    content: undefined,
    tags: ["code review", "teamwork"],
    sortIndex: 2,
  },
  {
    todoId: 103,
    title: "Update project documentation",
    description:
      "Add new sections to the project wiki covering recent feature updates.",
    status: {
      statusId: 7,
      statusCode: "CREATED",
      statusName: "Created",
      description: "Task has been created",
    },
    priority: Priority.LOW,
    dueDate: new Date("2024-07-03T23:59:59"),
    createdAt: new Date("2024-07-03T00:00:00"),
    updatedAt: new Date("2024-07-03T00:00:00"),
    files: [],
    content: undefined,
    tags: ["documentation", "wiki"],
    sortIndex: 3,
  },
  {
    todoId: 104,
    title: "Prepare for client meeting",
    description:
      "Create a presentation highlighting the progress and next steps for the project.",
    status: {
      statusId: 7,
      statusCode: "CREATED",
      statusName: "Created",
      description: "Task has been created",
    },
    priority: Priority.MEDIUM,
    dueDate: new Date("2024-07-04T23:59:59"),
    createdAt: new Date("2024-07-04T00:00:00"),
    updatedAt: new Date("2024-07-04T00:00:00"),
    files: [],
    content: undefined,
    tags: ["client", "meeting", "presentation"],
    sortIndex: 4,
  },
  {
    todoId: 105,
    title: "Optimize database queries",
    description: "Identify and optimize slow SQL queries in the application.",
    status: {
      statusId: 7,
      statusCode: "CREATED",
      statusName: "Created",
      description: "Task has been created",
    },
    priority: Priority.HIGH,
    dueDate: new Date("2024-07-05T23:59:59"),
    createdAt: new Date("2024-07-05T00:00:00"),
    updatedAt: new Date("2024-07-05T00:00:00"),
    files: [],
    content: undefined,
    tags: ["optimization", "database", "performance"],
    sortIndex: 5,
  },
];

export const demoMockCategorizedTodos = {
  CREATED: [demoMockTasksArray[1]],
  IN_PROGRESS: [demoMockTasksArray[0]],
  COMPLETED: [demoMockTasksArray[2]],
};
